name: Python application

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Укажите версию Python, которую вы хотите использовать

        
    - name: Install system dependencies
      run: sudo apt-get install -y libgl1-mesa-glx libegl1

      
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-glx libegl1 xvfb

        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Убедитесь, что у вас есть файл requirements.txt


    - name: Run service tests
      run: |
        pytest testing/tests/test_service.py --tb=short --disable-warnings
        

    - name: Run graphic tests
      run: |
        Xvfb :99 -screen 0 1920x1080x24 &
        export DISPLAY=:99
        pytest testing/tests/test_graphic.py --tb=short --disable-warnings
